name: Lint

on:
  pull_request:
  push:
    branches:
      - main
concurrency:
  group: '${{ github.workflow }}-${{ github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  linting:
    name: Run linters
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Yarn install
        uses: Wandalen/wretry.action@master
        with:
          command: yarn --frozen-lockfile
          attempt_limit: 3
          attempt_delay: 2000
      - name: Lint check
        run: yarn lint
      - name: Check & compile i18n
        run: yarn intl:build
      - name: Type check
        run: yarn typecheck
  testing:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - name: Install node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Check out Git repository
        uses: actions/checkout@v3
      - name: Yarn install
        uses: Wandalen/wretry.action@master
        with:
          command: yarn --frozen-lockfile
          attempt_limit: 3
          attempt_delay: 2000
      - name: Check & compile i18n
        run: yarn intl:build
      - name: Run tests
        uses: koenhagen/measure-energy-action@v0.33
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            NODE_ENV=test EXPO_PUBLIC_ENV=test yarn test --forceExit
          count: 1
